sudo: required
env:
  - CODECLIMATE_REPO_TOKEN=9a362578b1cf809b0f87ec02716761b9456f525c2e6e88c92333ba66b2bddd37
language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
# until https://github.com/travis-ci/apt-package-whitelist/issues/1370 is resolved
# addons:
#   apt:
#     packages:
#       - ifstat
before_install:
  - wget http://gael.roualland.free.fr/ifstat/ifstat-1.1.tar.gz
  - tar -zxf ifstat-1.1.tar.gz
  - cd ifstat-1.1
  - ./configure
  - make
  - sudo make install
after_script:
  - npm test --coverage
  - codeclimate-test-reporter < coverage/lcov.info
