env:
  - CODECLIMATE_REPO_TOKEN=9a362578b1cf809b0f87ec02716761b9456f525c2e6e88c92333ba66b2bddd37
language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
addons:
  apt:
    packages:
      - ifstat
after_script:
  - npm test --coverage
  - codeclimate-test-reporter < coverage/lcov.info
